development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://ejazhzjcazaqjd:YvaL4QCL83V0XqFOYPtjLMFqXT@ec2-23-23-192-249.compute-1.amazonaws.com:5432/d9r4539l047nf6
