# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Product.create(:name => "Onnit Hemp Force Active", :description => "Thundercats humblebrag 3 wolf moon unicorn chicharrones pabst, 90's fashion axe hella tumblr pok pok glossier affogato wolf. Prism leggings direct trade la croix kitsch, hot chicken vape jean shorts heirloom. Cray actually typewriter cred. Live-edge ramps readymade, tumeric deep v gluten-free pinterest. Forage lo-fi etsy cray, la croix neutra iceland letterpress actually DIY fap. Four dollar toast brooklyn tbh, church-key intelligentsia cray mumblecore hell of. Microdosing pickled flexitarian fap PBR&B, meggings kinfolk wayfarers.", :image_url => "onnit_hemp_force.jpg", :price => "$$$")
Product.create(:name => "WOD Welder Starter Kit", :description => "Thundercats humblebrag 3 wolf moon unicorn chicharrones pabst, 90's fashion axe hella tumblr pok pok glossier affogato wolf. Prism leggings direct trade la croix kitsch, hot chicken vape jean shorts heirloom. Cray actually typewriter cred. Live-edge ramps readymade, tumeric deep v gluten-free pinterest. Forage lo-fi etsy cray, la croix neutra iceland letterpress actually DIY fap. Four dollar toast brooklyn tbh, church-key intelligentsia cray mumblecore hell of. Microdosing pickled flexitarian fap PBR&B, meggings kinfolk wayfarers.", :image_url => "WOD-Welder-Starter.jpg", :price => "$$$")
Product.create(:name => "WOD Welder Starter Kit", :description => "Thundercats humblebrag 3 wolf moon unicorn chicharrones pabst, 90's fashion axe hella tumblr pok pok glossier affogato wolf. Prism leggings direct trade la croix kitsch, hot chicken vape jean shorts heirloom. Cray actually typewriter cred. Live-edge ramps readymade, tumeric deep v gluten-free pinterest. Forage lo-fi etsy cray, la croix neutra iceland letterpress actually DIY fap. Four dollar toast brooklyn tbh, church-key intelligentsia cray mumblecore hell of. Microdosing pickled flexitarian fap PBR&B, meggings kinfolk wayfarers.", :image_url => "WOD-Welder-Starter.jpg", :price => "$$$")